export default {
    unit1: {
        "senora": "ma’am",
        "mucho gusto": "nice to meet you",
        "hasta manana": "see you tomorrow",
        "adios": "bye",
        "hasta luego": "see you later",
        "buenas tardes": "good afternoon",
        "hola": "hello",
        "senorita": "Miss",
        "tu": "you",
        "usted": "you (formal)",
        "mal": "unwell",
        "ocupado": "busy",
        "perdon": "excuse me",
        "feliz": "happy",
        "muy": "very",
        "la banana": "the banana",
        "el te": "the tea",
        "el cafe": "the coffee",
        "mas": "more",
        "el taxi": "the taxi",
        "el dinero": "the money",
        "necesitas": "do you need",
        "el carro": "the car",
        "ayuda": "help",
        "el telefono": "the telephone",
        "el boligrafo": "the pen",
        "la computadora": "the computer",
        "uso/usas/usa": "use",
        "nuevo": "new",
        "videojuego": "video game",
        "divertido": "fun",
        "vamos": "we are going",
        "ver": "to watch",
        "pero": "but"
    },
    unit2: {
        "que": "what",
        "hoy": "today",
        "fiesta": "party",
        "cuando": "when",
        "cumpleaños": "birthday",
        "sábado": "Saturday",
        "mi": "my",
        "partido": "game",
        "concierto": "concert",
        "trabaja": "work",
        "vives": "live",
        "Inglaterra": "England",
        "lunes": "Monday",
        "martes": "Tuesday",
        "mañana": "tomorrow",
        "fútbol": "football",
        "jueves": "Thursday",
        "viernes": "Friday",
        "miércoles": "Wednesday",
        "béisbol": "baseball",
        "día": "day",
        "domingo": "Sunday",
        "divertida": "fun",
        "la película": "the movie",
        "baile": "dance",
        "favorita": "favorite",
        "semana": "week",
        "disfruta": "enjoy",
        "jugador": "player",
        "nervioso": "nervous",
        "pero": "but",
        "mismos": "same",
        "encantan": "love",
        "acá": "here",
        "matemáticas": "mathematics",
        "listo": "ready",
        "entra": "enters",
        "chicos": "guys",
        "cosas": "things",
        "vamos": "going to",
        "camina": "walks",
        "puerta": "door",
        "error": "mistake",
        "mira": "watch",
        "cocina": "cooking",
        "piensas": "you think"
    },
    unit3: {
        "camarero/camarera": "waiter/waitress",
        "médico/médica": "doctor",
        "amigo": "friend",
        "biblioteca": "library",
        "maestro": "teacher",
        "portugués": "Portuguese",
        "el celular": "the cell phone",
        "joven": "young",
        "número": "number",
        "dirección": "direction/address",
        "ser": "be",
        "el gato": "the cat",
        "el perro": "the dog",
        "la ciudad": "the city",
        "importante": "important",
        "la familia": "the family",
        "novio": "boyfriend",
        "hermano": "brother",
        "con": "with",
        "novia": "girlfriend",
        "hermana": "sister",
        "pueblo": "town",
        "caro": "expensive",
        "dos": "two",
        "uno": "one",
        "tres": "three",
        "cero": "zero",
        "bolígrafos": "pens",
        "escribir": "to write",
        "quién": "who",
        "la universidad": "the university",
        "cuatro": "four",
        "computadoras": "computers",
        "pregunta": "question",
        "cinco": "five",
        "aprende": "learn",
        "seis": "six",
        "siete": "seven",
        "ocho": "eight",
        "clase": "class",
        "estudiantes": "students",
        "le da": "gives",
        "abre": "open",
        "encantan": "love",
        "gracioso": "fun",
        "sé": "know",
        "olvidar": "forget"
    },
    unit4: {
        "la madre": "the mother",
        "el padre": "the father",
        "su": "his",
        "inteligente": "intelligent",
        "bonita": "pretty",
        "italiano": "Italian",
        "la esposa": "the wife",
        "el esposo": "the husband",
        "hijos": "children",
        "la hija": "the daughter",
        "el hijo": "the son",
        "pequeño": "small",
        "alto": "tall",
        "bajo": "short",
        "mascota": "pet",
        "simpática": "nice",
        "la abuela": "the grandmother",
        "el abuelo": "the grandfather",
        "diez": "ten",
        "nueve": "nine"
    },
    unit8: {
        "La jefa/el jefe": "The boss",
        "mensajes": "messages",
        "las secretarias": "the secretaries",
        "el escritorio": "the desk",
        "la carta": "the letter",
        "cuál": "which",
        "correo electrónico": "email address",
        "poco": "little",
        "ahora": "now",
        "nuevo": "new",
        "famosa": "famous",
        "receta": "recipe",
        "cocina": "kitchen",
        "cocinando": "cooking",
        "comida": "food",
        "vieja": "old",
        "secreto": "secret",
        "arroz": "rice",
        "después": "then",
        "pimienta": "pepper",
        "solo": "just",
        "aceite": "oil",
        "huevos": "eggs",
        "saber": "to know"
    },
    unit9: {
        "dormir": "to sleep",
        "preocupado": "worried",
        "también": "also / too",
        "te sientes": "to feel",
        "enfermo": "sick",
        "triste": "sad",
        "tal": "such",
        "emocionada": "excited",
        "contigo": "with you",
        "siempre": "always",
        "conmigo": "with me",
        "enojada": "angry",
        "aburrido": "bored",
        "el papá": "the dad",
        "nunca": "never",
        "a veces": "sometimes",
        "contenta": "happy",
        "la mamá": "the mom",
        "el bebé": "the baby",
        "otra vez": "again",
        "sorprendido": "surprised",
        "hace": "does",
        "ejercicio": "exercise",
        "videojuegos": "video games",
        "ir": "to go",
        "habitación": "bedroom",
        "corre": "runs",
        "llaves": "keys",
        "vamos": "let’s go",
        "último": "last",
        "piso": "floor",
        "vuelve": "returns"
    },
    unit10: {
        "las mujeres": "the women",
        "los hombres": "the men",
        "nosotros/nosotras": "we",
        "el jugador": "the player",
        "muchos": "many",
        "cuántos/cuántas": "how many",
        "vacaciones": "vacations",
        "unos": "some",
        "jardín": "garden",
        "visita": "visits",
        "habitación": "room",
        "salir": "go out",
        "sol": "sun",
        "idea": "idea",
        "momento": "moment",
        "minutos": "minutes",
        "después": "later/then",
        "plantas": "plants",
        "entra": "enters",
        "flores": "flowers",
        "básico": "basic",
        "hay": "there is",
        "televisión": "television",
        "de verdad": "really",
        "no voy": "I am not going",
        "bueno": "good",
        "bien": "well"
    },
    unit11: {
        "pantalones": "pants",
        "la camiseta": "the shirt",
        "el vestido": "the dress",
        "camisetas": "t-shirts",
        "interesante": "interesting",
        "los zapatos": "the shoes",
        "nuevos": "new",
        "el rojo": "the red",
        "pequeños": "small",
        "cita": "date",
        "frío": "cold",
        "chica": "girl",
        "estación": "station",
        "toma": "takes",
        "maneja": "drives",
        "empieza": "starts",
        "abre": "opens"
    },
    unit12: {
        "el tren": "the train",
        "cerca": "close",
        "viajar": "to travel",
        "estación": "station",
        "el hotel": "the hotel",
        "el parque": "the park",
        "el autobús": "the bus",
        "la puerta": "the door",
        "al lado de": "next to",
        "lejos": "far",
        "supermercado": "supermarket",
        "parada": "stop",
        "el banco": "the bank",
        "el hospital": "the hospital",
        "tomo": "takes",
        "la izquierda": "the left",
        "la derecha": "the right",
        "metro": "subway",
        "le": "gives",
        "momento": "moment",
        "llama": "calls",
        "taller": "shop",
        "ignora": "ignores",
        "entonces": "so"
    },
    unit13: {
        "caminar": "to walk",
        "playa": "beach",
        "el periódico": "the newspaper",
        "tarde": "afternoon/evening",
        "el pollo": "the chicken",
        "el arroz": "the rice",
        "bueno": "good",
        "la comida": "the food",
        "el verano": "the summer",
        "abrir": "to open",
        "juntas": "together",
        "decisión": "decision",
        "hambre": "hungry",
        "fritas": "fries",
        "solo": "only",
        "saludable": "healthy",
        "largo": "long",
        "abre": "opens",
        "recibir": "to receive",
        "nadar": "to swim"
    },
    unit14: {
        "toma": "takes",
        "popular": "popular",
        "salen": "they leave",
        "tenemos": "we have",
        "responsable": "responsible",
        "entonces": "then",
        "limpiar": "to clean",
        "lavar": "to wash",
        "ventanas": "windows",
        "después": "later",
        "horas": "hours",
        "termina": "finishes"
    },
    unit15: {
        "el chocolate": "the chocolate",
        "el pastel": "the cake",
        "porque": "because",
        "la falda": "the skirt",
        "algo": "something",
        "creo": "I think",
        "esa": "that",
        "pero": "but",
        "la piscina": "the pool",
        "nadar": "to swim",
        "dibujar": "to draw",
        "jugar": "to play",
        "correr": "to run",
        "viejo": "old",
        "música": "music",
        "modelo": "model",
        "entrar": "to enter",
        "arte": "art",
        "silla": "chair",
        "silencio": "silence",
        "actividad": "activity",
        "mostrador": "counter",
        "país": "country",
        "listo": "ready"
    },
    unit16: {
        "levantas": "do you get up",
        "la noche": "the night",
        "a menudo": "often",
        "vas": "are you going to",
        "cine": "movies",
        "todos": "everyone",
        "elevan": "elevate",
        "la televisión": "the television",
        "días": "days",
        "ocho y media": "eight thirty",
        "mirar": "to watch",
        "ducho": "I shower",
        "horas": "hours",
        "doce": "twelve",
        "a las": "at",
        "retrato": "portrait",
        "pinta": "paints",
        "cabello": "hair",
        "cabeza": "head",
        "tan": "so",
        "nariz": "nose",
        "pasa": "passes by"
    },
    unit17: {
        "salas": "living room",
        "modernas": "modern",
        "habitaciones": "bedrooms",
        "estanterías": "bookcases",
        "sillas": "chairs",
        "cocina": "kitchen",
        "nevera": "fridge",
        "tenedor": "fork",
        "pared": "wall",
        "costumbre": "custom",
        "luz": "light",
        "la cama": "the bed",
        "hay": "there is",
        "la ventana": "the window",
        "sobre": "on top of",
        "pintar": "to paint",
        "limpiar": "to clean",
        "la planta": "the plant",
        "el jardín": "the garden",
        "debajo": "underneath",
        "foto": "photo",
        "arte": "art",
        "ve a": "sees",
        "sociales": "social",
        "reunión": "meeting",
        "otros": "others",
        "enfrente": "in front of",
        "espere": "wait",
        "publicada": "published"
    },
    unit18: {
        "puede": "can",
        "traer": "bring",
        "menú": "menu",
        "bebidas": "drinks",
        "cervezas": "beers",
        "quisiera": "I would like",
        "postre": "dessert",
        "otra": "another",
        "los frijoles": "the beans",
        "el plato": "the plate",
        "tenedor": "fork",
        "el cuchillo": "the knife",
        "la cuchara": "the spoon",
        "blanco": "white",
        "la botella": "the bottle",
        "tinto": "red",
        "sopa": "soup",
        "la patata": "the potato",
        "frita": "fried",
        "deporte": "sport",
        "practicar": "practice",
        "baloncesto": "basketball",
        "tenis": "tennis",
        "empieza": "starts"
    },
    unit19: {
        "mayor": "old",
        "guitarra": "guitar",
        "escuchar": "to listen",
        "música": "music",
        "los abuelos": "the grandparents",
        "los padres": "the parents",
        "nuestro": "our",
        "el baloncesto": "basketball",
        "deporte": "sport",
        "el piano": "the piano",
        "clásica": "classic/traditional",
        "tocar": "to play",
        "el marido": "the husband",
        "menores": "younger",
        "dinosaurios": "dinosaurs",
        "tarea": "homework",
        "popular": "popular",
        "talla": "size",
        "probador": "fitting room",
        "precio": "price",
        "cara": "expensive",
        "el dólar": "the dollar",
        "trece": "thirteen",
        "cuesta": "costs",
        "catorce": "fourteen",
        "quince": "fifteen",
        "peso": "weight",
        "veinte": "twenty",
        "diecisiete": "seventeen",
        "dieciocho": "eighteen",
        "diecinueve": "nineteen",
        "dieciséis": "sixteen",
        "en efectivo": "in cash",
        "la tarjeta de crédito": "the credit card",
        "motocicleta": "motorcycle",
        "extraño": "strange",
        "cena": "dinner",
        "tarde": "late",
        "piso": "floor",
        "vuelve": "returns",
        "último": "last",
        "abiertos": "open",
        "limpios": "clean",
        "sucio": "dirty"
    },
    unit21: {
        "nerviosas": "nervous",
        "perezoso": "lazy",
        "probador": "fitting room",
        "abierta": "open",
        "rubio": "blond",
        "morenas": "dark-haired",
        "guapos": "good-looking",
        "jardín": "garden",
        "visita": "visits",
        "sol": "sun",
        "después": "later",
        "monos": "monkeys",
        "zoológico": "zoo",
        "elefantes": "elephants",
        "rápido": "fast",
        "odias": "hate",
        "helado": "ice cream"
    },
    unit22: {
        "aquella": "that",
        "tenis": "tennis",
        "tiempo": "time",
        "normalmente": "normally",
        "pasa": "spends",
        "el caballo": "the horse",
        "la pelota": "the ball",
        "río": "river",
        "caminas": "are you walking",
        "montar": "to ride"
    },
    unit23: {
        "visitar": "to visit",
        "Alemania": "Germany",
        "país": "country",
        "la gente": "the people",
        "lugar": "place",
        "parte": "part",
        "diferente": "different",
        "usualmente": "usually",
        "algunos": "some",
        "la tele": "the TV",
        "amas": "do you love",
        "veo": "watch",
        "enseñar": "to teach",
        "hambre": "hungry",
        "especial": "special",
        "botella": "bottle",
        "derrama": "spills",
        "toda": "whole",
        "torre": "tower"
    },
    unit24: {
        "hambre": "hungry",
        "sed": "thirsty",
        "frío": "cold",
        "veinte": "twenty",
        "veintiuno": "twenty-one",
        "adultos": "adults",
        "veintidós": "twenty-two",
        "la pizza": "the pizza",
        "veinticinco": "twenty-five",
        "veinticuatro": "twenty-four",
        "veintitrés": "twenty-three",
        "calor": "hot",
        "puesto": "place/position",
        "largo": "long",
        "miedo": "fear",
        "sueño": "sleepy",
        "bailar": "to dance",
        "animales": "animals",
        "horror": "horror"
    },
    unit25: {
        "muñeca": "doll",
        "idiomas": "languages",
        "curso": "course",
        "flores": "flowers",
        "nada": "nothing",
        "tarde": "late",
        "entonces": "then",
        "estornuda": "sneezes",
        "alérgico": "allergic",
        "ojos": "eyes"
    }
}