export default {
    unit1: {
        "el niño": "the boy",
        "la niña": "the girl",
        "buenos días": "good morning",
        "buenas noches": "good night",
        "hola": "hello",
        "mucho gusto": "nice to meet you",
        "cama": "bed",
        "leche": "milk",
        "niño": "boy",
        "niña": "girl",
        "como / comes": "eat",
        "el pan": "bread",
        "bebo / bebes / bebe": "drink",
        "mujer": "woman",
        "hombre": "man",
        "es": "it is",
        "agua": "water",
        "adios": "bye",
        "gracias": "thank you",
        "buenos días": "good morning",
        "de nada": "you’re welcome",
        "perdón": "excuse me / pardon",
        "lo siento": "I am sorry / sorry",
        "sí": "yes",
        "por favor": "please",
        "no": "no",
        "español": "Spanish",
        "inglés": "English",
        "disculpe": "excuse me",
        "hablo / hablas": "speak"
    },
    unit2: {
        "el niño": "the boy",
        "la niña": "the girl",
        "buenos días": "good morning",
        "buenas noches": "good night",
        "hola": "hello",
        "mucho gusto": "nice to meet you",
        "cama": "bed",
        "leche": "milk",
        "niño": "boy",
        "niña": "girl",
        "como / comes": "eat",
        "el pan": "bread",
        "bebo / bebes / bebe": "drink",
        "mujer": "woman",
        "hombre": "man",
        "es": "it is",
        "agua": "water",
        "adiós": "bye",
        "gracias": "thank you",
        "de nada": "you’re welcome",
        "perdón": "excuse me / pardon",
        "lo siento": "I am sorry / sorry",
        "sí": "yes",
        "por favor": "please",
        "no": "no",
        "español": "Spanish",
        "inglés": "English",
        "disculpe": "excuse me",
        "hablo / hablas": "speak",
        "necesito": "need",
        "donde": "where",
        "aquí": "here",
        "pasaporte": "passport",
        "boleto": "ticket",
        "a": "to",
        "cerrado": "closed",
        "amarillo": "yellow",
        "para": "for",
        "dos": "two",
        "personas": "people",
        "con o sin": "with or without",
        "café": "coffee",
        "quiero": "want",
        "ensalada": "salad",
        "tomate": "tomato",
        "sándwich": "sandwich",
        "pescado": "fish",
        "jugo": "juice",
        "naranja": "orange",
        "taza": "cup",
        "el teléfono": "the phone",
        "mi": "my",
        "maleta": "suitcase",
        "hotel": "hotel",
        "en": "in",
        "tengo": "have",
        "reserva": "reservation",
        "el aeropuerto": "the airport",
        "el tren": "the train",
        "el dinero": "the money",
        "el autobús": "the bus",
        "tu": "your",
        "el banco": "the bank",
        "el hospital": "the hospital",
        "el museo": "the museum",
        "el baño": "the bathroom",
        "calle": "street",
        "supermercado": "super market",
        "el restaurante": "the restaurant",
        "tres": "three",
        "uno": "one",
        "la mesa": "the table",
        "las personas": "the people",
        "la carne": "the meat",
        "el queso": "the cheese",
        "con": "with",
        "de": "made of",
        "hamburguesa": "burger",
        "el vaso": "the glass",
        "el azúcar": "the sugar",
        "la sal": "the salt",
        "la cuenta": "the check",
        "pagar": "to pay"
    },
    unit3: {
        "tiene / tienes": "have",
        "perro": "dog",
        "gato": "cat",
        "grande": "big",
        "quiero": "want",
        "camisa": "shirt",
        "verde": "green",
        "azul": "blue",
        "vestido": "dress",
        "rojo": "red",
        "cartera": "purse",
        "gris": "grey",
        "marrón": "brown",
        "reloj": "watch",
        "caro": "expensive",
        "barato": "cheap",
        "la casa": "the house",
        "la madre": "the mother",
        "el padre": "the father",
        "el carro": "the car",
        "elegante": "elegant",
        "inteligente": "intelligent",
        "familia": "family",
        "hermana": "sister",
        "hermano": "brother",
        "muy": "very",
        "bonito": "pretty",
        "el esposo": "the husband",
        "la esposa": "the wife",
        "el abuelo": "the grandfather",
        "la abuela": "the grandmother",
        "perfecto": "perfect",
        "la bicicleta": "the bicycle",
        "hijo": "son",
        "hija": "daughter",
        "vivo": "live",
        "interesante": "interesting",
        "y": "and",
        "un animal": "an animal",
        "mi / mis": "my",
        "amor": "love",
        "están": "are",
        "llaves": "keys",
        "ir": "to go",
        "trabajo": "work",
        "cansada": "tired",
        "su": "her",
        "que": "what",
        "eso / ese": "that",
        "no con": "not with",
        "la tienda": "the store",
        "la ropa": "the clothes",
        "chaqueta": "the jacket",
        "el sombrero": "the hat",
        "la camiseta": "the t-shirt",
        "este": "this",
        "comprar": "to buy",
        "el abrigo": "the coat",
        "la falda": "the skirt",
        "diferente": "different",
        "el cinturón": "the belt",
        "el regalo": "the gift",
        "demasiado": "too",
        "cómoda": "comfortable",
        "favorita": "favorite",
        "cita": "date",
        "deportes": "sports",
        "te gustan": "do you like",
        "juego": "play",
        "también": "also",
        "súper": "great",
        "encanta": "love",
        "mascotas": "pets",
        "camina": "walks",
        "cosa": "thing",
        "nieta": "granddaughter",
        "idea": "idea"
    },
    unit4: {
        "hablo / hablas / habla": "speak",
        "el maestro": "the teacher",
        "el libro": "the book",
        "la escuela": "the school",
        "el bolígrafo": "the pen",
        "fácil": "easy",
        "examen": "exam",
        "clase": "class",
        "la pregunta": "the question",
        "el estudiante": "the student",
        "leer / leo": "to read",
        "difícil": "difficult",
        "escribir / escribo": "to write",
        "estudiar / estudio": "to study",
        "problema": "problem",
        "comprendo": "understand",
        "importante": "important",
        "la computadora": "the computer",
        "la medicina": "the medicine",
        "profesor": "the professor",
        "universidad": "university",
        "conocer": "to meet",
        "va": "going to",
        "solo": "only",
        "novia": "girlfriend",
        "pero": "but",
        "ahora": "now",
        "bienvenida": "welcome",
        "encanta": "love",
        "cuesta": "costs",
        "quinientos": "five hundred",
        "dólares": "dollars",
        "mejor amiga": "best friend",
        "cumpleaños": "birthday"
    },
    unit5: {
        "china": "China",
        "españa": "Spain",
        "los estados unidos": "The United States",
        "de": "from",
        "francia": "France",
        "americano / americana": "American",
        "el estudiante": "the student",
        "y": "and",
        "donde": "where",
        "nombre": "name",
        "vivo": "live",
        "en": "in",
        "méxico": "Mexico",
        "cubano / cubana": "Cuban",
        "vacaciones": "vacation",
        "luna": "honeymoon",
        "conmigo": "with me",
        "triste": "sad",
        "corre": "runs",
        "vamos": "let’s go",
        "ir": "to go"
    }
}